
[platformio]
default_envs = ec2
; uncomment this line to build on Macbook local dir instead of NFS mount
workspace_dir = /var/tmp/stw
upload_speed = 460800
monitor_speed = 115200

[common]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = nodemcu-32s
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_type = release
board_build.partitions = medspiffs.csv
board_build.filesystem = littlefs
build_flags =
	-D HOSTNAME=st-wind
	-D ELEGANTOTA
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D WEBSERIAL
	-D WIFI
	-D WEB
	-D SEATALK
	-D N2K
;	-D NMEA
	-Os
	-ffunction-sections
	-fdata-sections
lib_compat_mode = strict
lib_ldf_mode = deep
lib_deps = 
	https://github.com/ESP32Async/AsyncTCP
	https://github.com/ESP32Async/ESPAsyncWebServer
	https://github.com/ayushsharma82/ElegantOTA
	bblanchon/ArduinoJson@^7.2.0
	sui77/rc-switch@^2.6.4
	https://github.com/plerup/espsoftwareserial.git#7.0.0
	ttlappalainen/NMEA2000-library@4.21.5
	https://github.com/wjquigs11/NMEA2000_esp32

[env:macbook]
extends = common
board = esp32dev
build_flags =
    ${common.build_flags}
	-D LED_BUILTIN=2
lib_deps =
	${common.lib_deps}
	/Users/wjquigs/Dropbox/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip

[env:graviton]
extends = common
board = esp32dev
build_flags =
    ${common.build_flags}
	-D LED_BUILTIN=2
lib_deps =
	${common.lib_deps}
	/home/wjquigs/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip

[env:ec2]
extends = common
board = esp32dev
build_flags =
    ${common.build_flags}
	-D LED_BUILTIN=2
lib_deps =
	${common.lib_deps}
	/home/ec2-user/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
